version: '3'

services:
  web:
    build: ./Web
    environment:
      - DJANGO_SUPERUSER_PASSWORD=9875023
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:8.0.29
    ports:
      - '3303:3306'
    environment:
      MYSQL_DATABASE: 'socialDB'
      MYSQL_USER: 'margo'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql