# Generated by Django 3.2.3 on 2021-08-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_add_test_to_Author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='test',
        ),
    ]
